### ISSUE TITLE
如果首页视频多了之后，滑动多个后会出现内存溢出如何处理？

### ISSUE THREAD

**Issue by Rosslrs** [MIkeeJY/honglou#4]

**Comment by MIkeeJY** [comment]
请问下大概是多少视频左右和具体机型会发生OOM

**Comment by MIkeeJY** [comment]
我用Nexus 5x在加载了200多条数据后尚未出现OOM的问题
![image](https://user-images.githubusercontent.com/8580762/56179638-0aaca600-6039-11e9-803d-58b85188010a.png)
![image](https://user-images.githubusercontent.com/8580762/56179647-1730fe80-6039-11e9-99cc-1d944fae8534.png)
基于fresco自身内存回收机制，还有这种接口设计理论上不应该是无限滑动 不然再好的应用无限加载更多 在数据过大的时候也可能出现OOM

**Comment by Rosslrs** [comment]
如果是稍微低配一点的手机70个左右就会出现闪退了

**Comment by MIkeeJY** [comment]
@Rosslrs nexus5x运行某些应用已经够卡顿了，其实首页还是还是可以进行一些优化的，你可以用低配的手机试试别的应用。。。

**Comment by Rosslrs** [comment]
是VerticalVideoActivity这个类里面的播放视频不停的下滑，不是在首页

**Comment by MIkeeJY** [comment]
@Rosslrs 二级页面用的verticalviewpager 暂时没有实现view的重用，都是remove再add的 需要变更实现方式
