### ISSUE TITLE
服务器

### ISSUE THREAD

**Issue by XiongKexin1997** [MIkeeJY/honglou#6]
怎么连接到自己的服务器，需要做哪些修改？

**Comment by MIkeeJY** [comment]
目前破解的是旧版抖音的接口- -，是直接连头条的服务器

**Comment by XiongKexin1997** [comment]
谢谢，那如果想连自己的服务器给APP推送视频链接什么的需要做哪些修改呢？

**Comment by MIkeeJY** [comment]
@XiongKexin1997 推送只需要视频的url啊~

**Comment by XiongKexin1997** [comment]
谢谢解答 ! 完全小白，打扰了，感觉数据很难对齐，服务器只发视频url和标题什么的，app接受不到其他的数据会出错吗，是不是需要把不需要的都删掉？

**Comment by MIkeeJY** [comment]
建议你使用三方推送 看下 对应推送内容的intent~
